# Generated by Django 2.2.2 on 2019-06-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('booking_date', models.DateField(auto_now=True)),
                ('booking_place', models.CharField(max_length=100)),
                ('booking_receiver', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('user_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.IntegerField()),
            ],
        ),
    ]
