# Generated by Django 2.2.2 on 2019-06-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_bookings_user_user_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
