# Generated by Django 2.2.2 on 2019-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='last_name', max_length=100),
            preserve_default=False,
        ),
    ]
